import {describe,expect,it} from "vitest";
import {campaignRowsDirty,filterCampaignRows,moveCampaignRow,paginateCampaignRows,serializeCampaignRows,updateCampaignRow,type CampaignTableRow} from "./campaign-table-model";
const row=(i:number,status:CampaignTableRow["availabilityStatus"]="unconfirmed"):CampaignTableRow=>({productId:`00000000-0000-4000-8000-${String(i).padStart(12,"0")}`,productVariantId:null,importPresentationId:`10000000-0000-4000-8000-${String(i).padStart(12,"0")}`,productName:`Producto ${i}`,variantLabel:null,presentationLabel:`${i} ml`,priceAmount:`${i}.00`,availabilityStatus:status});
describe("898-line campaign table model",()=>{
 it("renders a bounded window",()=>{const rows=Array.from({length:898},(_,i)=>row(i+1));const page=paginateCampaignRows(rows,2,40);expect(page.items).toHaveLength(40);expect(page.from).toBe(41);expect(page.to).toBe(80);expect(page.pages).toBe(23);});
 it("filters locally without changing the authoritative set",()=>{const rows=[row(1),row(2,"available"),row(3)];expect(filterCampaignRows(rows,"Producto 2","available")).toEqual([rows[1]]);expect(rows).toHaveLength(3);});
 it("a filtered edit mutates the matching row in the full array and save serializes all",()=>{const rows=Array.from({length:898},(_,i)=>row(i+1));const visible=filterCampaignRows(rows,"Producto 777","all");const edited=updateCampaignRow(rows,`${visible[0]!.productId}::::${visible[0]!.importPresentationId}`,{priceAmount:"99.50"});const payload=serializeCampaignRows(edited);expect(payload).toHaveLength(898);expect(payload[776]!.priceAmount).toBe("99.50");expect(payload[0]!.priceAmount).toBe("1.00");});
 it("move-to-position preserves every row exactly once",()=>{const rows=Array.from({length:30},(_,i)=>row(i+1));const moved=moveCampaignRow(rows,`${rows[20]!.productId}::::${rows[20]!.importPresentationId}`,2);expect(moved).toHaveLength(30);expect(new Set(moved.map(x=>x.productId)).size).toBe(30);expect(moved[1]!.productId).toBe(rows[20]!.productId);});
 it("dirty detection notices values and ordering but not identical clones",()=>{const rows=[row(1),row(2)];expect(campaignRowsDirty(rows,rows.map(x=>({...x})))).toBe(false);expect(campaignRowsDirty(rows,updateCampaignRow(rows,`${rows[0]!.productId}::::${rows[0]!.importPresentationId}`,{availabilityStatus:"available"}))).toBe(true);expect(campaignRowsDirty(rows,[rows[1]!,rows[0]!])).toBe(true);});
});
