import type{Metadata,Route}from"next";import Link from"next/link";import{notFound,redirect}from"next/navigation";import{getAdminSession}from"@/lib/auth/admin-session";import{createSupabaseServerClient}from"@/lib/supabase/server";import{AdminImportCatalogRepository}from"@/domains/admin-import/catalog-repository";import{AdminParfumsMediaRepository}from"@/domains/admin-parfums/media-repository";import{PRODUCT_STATUS_LABELS}from"@/domains/admin-import/catalog-schema";import{ImportProductEditor}from"../import-product-editor";import{ImportMediaManager}from"../import-media-manager";import styles from"../page.module.css";
export const dynamic="force-dynamic";export const metadata:Metadata={title:"Detalle producto Import"};
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){const s=await getAdminSession();if(s.status==="signed_out")redirect("/admin/login");if(s.status!=="ok")redirect("/admin");const m=s.session.memberships.find(x=>x.businessUnitCode==="import");if(!m)redirect("/admin");const c=await createSupabaseServerClient();if(!c)redirect("/admin");const{id}=await params;const rawParams=await searchParams;
// The campaign context is whatever the caller (Productos/Publicacion deep
// link) explicitly selected via ?campaign=. Only when NONE is supplied do
// we default to the latest non-archived campaign, for convenience — a
// campaign chosen upstream is NEVER silently re-inferred to something else.
const requestedCampaignId=typeof rawParams.campaign==="string"?rawParams.campaign:null;
let campaignId=requestedCampaignId;
if(!campaignId){const defaultCampaign=await c.from("campaigns").select("id").eq("business_unit_id",m.businessUnitId).is("archived_at",null).order("number",{ascending:false}).limit(1).maybeSingle();campaignId=defaultCampaign.data?.id??null;}
const catalogRepo=new AdminImportCatalogRepository(c,m.businessUnitId);const mediaRepo=new AdminParfumsMediaRepository(c);const[r,mr]=await Promise.all([catalogRepo.get(id,campaignId),mediaRepo.listForProduct(id)]);if(!r.ok){if(r.error.type==="not_found")notFound();return <main className={styles.page}><p className={styles.error}>No se pudo cargar este producto.</p></main>}const d=r.data;const media=mr.ok?mr.data:[];return <div className={styles.page}><header className={styles.header}><div><Link className={styles.back} href={(campaignId?`/admin/import/productos?campaign=${campaignId}`:"/admin/import/productos") as Route}>← Productos</Link><h1>{d.product.name}</h1><p>{d.product.brand??"Sin marca"} · {d.category?.name??"Sin categoría"}</p></div><span className={styles.badge}>{PRODUCT_STATUS_LABELS[d.product.publication_status as keyof typeof PRODUCT_STATUS_LABELS]??d.product.publication_status}</span></header><main><section className={styles.panel}><h2>Identidad y procedencia</h2><dl className={styles.facts}><div><dt>Identificador del catálogo</dt><dd className={styles.identity}>{d.product.slug}</dd></div><div><dt>Referencia de origen</dt><dd className={styles.identity}>{d.product.legacy_id??"No registrada"}</dd></div><div><dt>Verificación</dt><dd>{d.product.verification_status.replaceAll("_"," ")}</dd></div><div><dt>Ofertas en consolidado {d.activeCampaignNumber!==null?`#${d.activeCampaignNumber}`:"evaluado"}</dt><dd>{d.offerCount}</dd></div></dl><p className={styles.help}>Los identificadores de origen se conservan para mantener la trazabilidad del catálogo.</p></section><ImportProductEditor detail={d} readOnly={m.role==="viewer"}/><ImportMediaManager productId={d.product.id} media={media} disabled={m.role==="viewer"}/></main></div>}
