-- Cruzial Parfums — owner-delegated reversible launch merchandising (2026-10-01).
-- Operator-run, idempotent, data only. Requires migration 20261001010000.
-- GENERATED by scripts/gen-owner-launch-merchandising-sql.mjs from the committed
-- research artifacts; do not edit the VALUES by hand.
--
-- Authority: CLAUDE.md "Current owner delegation — reversible launch merchandising"
-- (2026-10-01). Everything here is a provisional, editable launch choice — never
-- recorded as client-confirmed or official — and every change is written to
-- audit_log (Admin -> Historial de cambios) with its evidence.
--
-- 1. 18 bottle variants whose identity, size and concentration are all CONFIRMED in
--    supabase/staging/bottle-identity-audit.json and whose price comes from >= 2
--    credible Peru sources in supabase/staging/bottle-market-research.json move
--    provisional_market -> owner_selected_provisional and are published. The guard
--    requires the stored price to still equal the researched value, so a price the
--    owner already edited is never touched.
--    NOT included (stay draft, a factual datum is unknown): bir-intense and
--    le-beau-le-parfum (bottle size), cedrat-boise-int and victory-elixir
--    (concentration / identity conflict), 1-million-lucky (single promotional
--    source) and by-the-fireplace (no credible Peru price).
-- 2. Products that only lack an OPTIONAL photo are published and show the site's
--    "Foto próximamente" fallback: lovely-cherry, royal-blend-sequoia,
--    sceptre-malachite. liquid-brun gets its two REAL client photos first.
--    le-male-le-parfum stays draft (no brand/gender on record).
--
-- Run: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/provisioning/parfums-owner-launch-merchandising.sql

begin;

create temporary table olm_prices (slug text, size_ml numeric, price numeric(12,2), evidence jsonb) on commit drop;
insert into olm_prices values
  ('9pm', 100, 206, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":206,"observations":[{"source":"Falabella Perú (marketplace: Perfumes Premium Peru)","price_pen":245.9,"seller_type":"tier2_marketplace_on_major_department_platform","date":"2026-09-13"},{"source":"PerfumesArabes.pe","price_pen":167,"seller_type":"tier3_specialist_arabic_perfume_store","date":"2026-09-13"}]}'::jsonb),
  ('adg-profondo-edp', 100, 329, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":329,"observations":[{"source":"Ripley Perú (vendido por Ripley)","price_pen":349,"seller_type":"tier2_department_store_direct","date":"2026-09-13"},{"source":"Perfumes Premium Peru","price_pen":309,"seller_type":"tier3_specialist_perfume_store","date":"2026-09-13"}]}'::jsonb),
  ('asad-elixir', 100, 168, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":168,"observations":[{"source":"Ripley Mercado (BERAUS IMPORT — Vendedor Destacado)","price_pen":189.9,"seller_type":"tier2_marketplace_featured_seller_on_major_department_platform","date":"2026-09-13"},{"source":"PlazaVea","price_pen":146,"seller_type":"tier2_department_store_direct","date":"2026-09-13"}]}'::jsonb),
  ('b-man-in-black', 100, 535, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":535,"observations":[{"source":"Ripley Mercado (Bono&Guerlan)","price_pen":549,"seller_type":"tier2_marketplace_on_major_department_platform","date":"2026-09-13"},{"source":"Beauty Store Peru","price_pen":520,"seller_type":"tier3_specialist_perfume_store","date":"2026-09-13"}]}'::jsonb),
  ('cdn-intense-man', 105, 207, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":207,"observations":[{"source":"Falabella Perú (marketplace: Perfumes Premium Peru)","price_pen":216.9,"seller_type":"tier2_marketplace_on_major_department_platform","date":"2026-09-13"},{"source":"Oechsle Perú","price_pen":197.1,"seller_type":"tier2_department_store_direct","date":"2026-09-13"}]}'::jsonb),
  ('dylan-blue', 100, 375, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"HIGH","selection_method":"median_of_2_credible_sources_exact_agreement","selected_reference_pen":375,"observations":[{"source":"Ripley Perú (vendido por Ripley)","price_pen":375.2,"seller_type":"tier2_department_store_direct","date":"2026-09-13"},{"source":"Falabella Perú","price_pen":375.2,"seller_type":"tier2_department_store_direct","date":"2026-09-13"}]}'::jsonb),
  ('erba-pura', 100, 919, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"HIGH","selection_method":"median_of_4_credible_sources","selected_reference_pen":919,"observations":[{"source":"Beauty Pacific Perú","price_pen":999,"seller_type":"tier3_specialist_perfume_store","date":"2026-09-13"},{"source":"Maison Niche Perú","price_pen":999,"seller_type":"tier3_specialist_perfume_store","date":"2026-09-13"},{"source":"Ripley Perú (marketplace)","price_pen":839.9,"seller_type":"tier2_marketplace_on_major_department_platform","date":"2026-09-13"},{"source":"OneMarie","price_pen":799,"seller_type":"tier3_specialist_perfume_store","date":"2026-09-13"}]}'::jsonb),
  ('erba-pura', 50, 667, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":667,"observations":[{"source":"Falabella Perú","price_pen":719,"seller_type":"tier2_department_store_direct","date":"2026-09-13"},{"source":"Ripley Perú (marketplace)","price_pen":615,"seller_type":"tier2_marketplace_on_major_department_platform","date":"2026-09-13"}]}'::jsonb),
  ('eros-edt', 100, 375, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"HIGH","selection_method":"median_of_2_credible_sources_exact_agreement","selected_reference_pen":375,"observations":[{"source":"Ripley Perú (vendido por Ripley)","price_pen":375.2,"seller_type":"tier2_department_store_direct","date":"2026-09-13"},{"source":"Falabella Perú","price_pen":375.2,"seller_type":"tier2_department_store_direct","date":"2026-09-13"}]}'::jsonb),
  ('hawas-ice', 100, 200, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"median_of_3_credible_sources","selected_reference_pen":200,"observations":[{"source":"Falabella Perú (marketplace: Thunder Parfum)","price_pen":199.99,"seller_type":"tier2_marketplace_on_major_department_platform","date":"2026-09-13"},{"source":"Maison Arabia","price_pen":249,"seller_type":"tier3_specialist_arabic_perfume_store","date":"2026-09-13"},{"source":"Eternal Parfum","price_pen":195,"seller_type":"tier3_specialist_perfume_store","date":"2026-09-13"}]}'::jsonb),
  ('khamrah-clasico', 100, 243, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":243,"observations":[{"source":"Falabella Perú (vendido por Falabella)","price_pen":258.24,"seller_type":"tier2_department_store_direct","date":"2026-09-13"},{"source":"Alamo Parfums Perú","price_pen":227,"seller_type":"tier3_specialist_peru_retailer","date":"2026-09-13"}]}'::jsonb),
  ('le-male-elixir', 75, 464, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":464,"observations":[{"source":"Falabella Perú","price_pen":439,"seller_type":"tier2_department_store_direct","date":"2026-09-13"},{"source":"Ripley Perú (product code 2014318406131p)","price_pen":489,"seller_type":"tier2_department_store_direct","date":"2026-09-13"}]}'::jsonb),
  ('liquid-brun', 100, 180, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":180,"observations":[{"source":"Falabella Perú (marketplace)","price_pen":159.9,"seller_type":"tier2_marketplace_on_major_department_platform","date":"2026-09-13"},{"source":"Ripley Perú (pmp20001178999)","price_pen":199.9,"seller_type":"tier2_department_store_direct","date":"2026-09-13"}]}'::jsonb),
  ('m-red-tobacco', 120, 609, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":609,"observations":[{"source":"Ripley Perú (marketplace: Bono&Guerlan)","price_pen":589,"seller_type":"tier2_marketplace_on_major_department_platform","date":"2026-09-13"},{"source":"Beauty Pacific Perú","price_pen":629,"seller_type":"tier3_specialist_peru_retailer","date":"2026-09-13"}]}'::jsonb),
  ('sauvage-edt', 100, 414, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":414,"observations":[{"source":"Passim Perú","price_pen":429,"seller_type":"tier3_specialist_perfume_store","date":"2026-09-13"},{"source":"RoyalLux Perú","price_pen":399,"seller_type":"tier3_specialist_perfume_store","date":"2026-09-13"}]}'::jsonb),
  ('spicebomb-extreme', 90, 598, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_sources","selected_reference_pen":598,"observations":[{"source":"Falabella Perú","price_pen":596.9,"seller_type":"tier2_department_store_direct","date":"2026-09-13"},{"source":"Oechsle Perú (marketplace: BONO&GUERLAN), product 1001508347","price_pen":599,"seller_type":"tier2_marketplace_on_major_department_platform","date":"2026-09-13"}]}'::jsonb),
  ('tmw-parfum', 100, 407, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"HIGH","selection_method":"median_of_3_credible_sources_exact_agreement","selected_reference_pen":407,"observations":[{"source":"Falabella Perú (vendido por Falabella)","price_pen":407.2,"seller_type":"tier2_department_store_direct","date":"2026-09-13"},{"source":"Ripley Perú (vendido por Ripley)","price_pen":407.2,"seller_type":"tier2_department_store_direct","date":"2026-09-13"},{"source":"Oechsle Perú (vendido por Oechsle)","price_pen":407.2,"seller_type":"tier2_department_store_direct","date":"2026-09-13"}]}'::jsonb),
  ('ultra-male', 125, 405, '{"source":"supabase/staging/bottle-market-research.json","research_date":"2026-09-13","confidence":"MEDIUM","selection_method":"midpoint_of_2_credible_currently_orderable_sources_rounded_to_integer_pen","selected_reference_pen":405,"observations":[{"source":"MM Parfum","price_pen":419,"seller_type":"tier3_specialist_peru_retailer","date":"2026-09-13"},{"source":"Royal King Perú","price_pen":390,"seller_type":"tier3_specialist_peru_retailer","date":"2026-09-13"}]}'::jsonb);

create temporary table olm_media (role text, sort_order integer, public_id text, secure_url text, width integer,
  height integer, bytes integer, format text, sha256 text, source_file text) on commit drop;
insert into olm_media values
  ('set', 0, 'cruzial/parfums/catalog/liquid-brun/set', 'https://res.cloudinary.com/iwwtyvf2/image/upload/v1790884398/cruzial/parfums/catalog/liquid-brun/set.png', 2048, 2048, 1180863, 'png', 'c3feea8b7ad88e9a9455c1dad8ff1064f1cdf96ec3e9ba54885f42e48096723f', 'FRENCH AVENEU -LIQUID BRUN.png'),
  ('bottle', 1, 'cruzial/parfums/catalog/liquid-brun/bottle', 'https://res.cloudinary.com/iwwtyvf2/image/upload/v1790884398/cruzial/parfums/catalog/liquid-brun/bottle.png', 2048, 2048, 1299037, 'png', '0497ed05ff59d4cdfd2015f6d3749c969d0e91c485b68a3137125c8f6af80702', 'FRENCH AVENEU - LIQUID BRUN.png');

-- 0. liquid-brun real client photos (role convention: set = bottle + vials, primary; bottle = bottle only)
insert into public.product_media (product_id, provider, public_id, secure_url, width, height, bytes, format, checksum,
  alt, sort_order, is_primary, metadata)
select p.id, 'cloudinary', m.public_id, m.secure_url, m.width, m.height, m.bytes, m.format, m.sha256,
  trim(concat_ws(' ', p.brand, p.name)), m.sort_order,
  (m.sort_order = 0 and not exists (select 1 from public.product_media x where x.product_id = p.id and x.archived_at is null and x.is_primary)),
  jsonb_build_object('legacy_id', p.slug, 'media_role', m.role, 'source_sha256', m.sha256,
    'source_file', m.source_file, 'migration_source', 'owner_delegation_launch_2026-10-01')
from public.products p
join public.business_units b on b.id = p.business_unit_id and b.code = 'parfums'
cross join olm_media m
where p.slug = 'liquid-brun' and p.archived_at is null
  and not exists (select 1 from public.product_media x where x.product_id = p.id and x.public_id = m.public_id);

-- 1. launch prices: provisional_market -> owner_selected_provisional (+ publish), audited
create temporary table olm_promoted on commit drop as
with target as (
  select v.id as variant_id, p.business_unit_id, p.slug, lp.evidence,
         jsonb_build_object('price_amount', v.price_amount, 'price_verification_status', v.price_verification_status,
                            'publication_status', v.publication_status) as before_state
  from olm_prices lp
  join public.products p on p.slug = lp.slug and p.archived_at is null
  join public.business_units b on b.id = p.business_unit_id and b.code = 'parfums'
  join public.product_variants v on v.product_id = p.id and v.variant_kind = 'bottle'
       and v.size_ml = lp.size_ml and v.archived_at is null
  where v.price_verification_status = 'provisional_market' and v.price_amount = lp.price
), promoted as (
  update public.product_variants v
  set price_verification_status = 'owner_selected_provisional', publication_status = 'published'
  from target t where v.id = t.variant_id
  returning v.id, v.price_amount
)
select t.variant_id, t.business_unit_id, t.slug, t.before_state, t.evidence, pr.price_amount
from target t join promoted pr on pr.id = t.variant_id;

insert into public.audit_log (business_unit_id, actor_user_id, action, entity_type, entity_id, before, after, request_id)
select business_unit_id, null, 'verification_update', 'product_variant', variant_id, before_state,
  jsonb_build_object('price_amount', price_amount, 'price_verification_status', 'owner_selected_provisional',
    'publication_status', 'published', 'decision', 'owner_delegated_initial_launch_price',
    'note', 'Precio inicial provisional elegido por el dueño (delegación 2026-10-01) a partir de la investigación de mercado; editable en Admin; no está confirmado por el cliente.',
    'evidence', evidence),
  'owner_launch_merchandising_2026-10-01'
from olm_promoted;

-- 2. products that lack only an optional photo (explicit allowlist; each must still pass the gate)
update public.product_variants v
set publication_status = 'published'
from public.products p
where v.product_id = p.id and p.slug in ('sceptre-malachite') and p.archived_at is null
  and v.archived_at is null and v.variant_kind = 'decant' and v.publication_status = 'draft'
  and v.currency = 'PEN' and v.price_amount > 0 and v.price_verification_status in ('official_pdf', 'client_confirmed');

create temporary table olm_products on commit drop as
with ready as (
  select p.id, p.business_unit_id, p.slug
  from public.products p
  join public.business_units b on b.id = p.business_unit_id and b.code = 'parfums'
  where p.slug in ('lovely-cherry', 'royal-blend-sequoia', 'sceptre-malachite', 'liquid-brun')
    and p.archived_at is null and p.publication_status = 'draft'
    and p.gender in ('women', 'men', 'unisex') and coalesce(p.brand, '') <> '' and coalesce(p.name, '') <> ''
    and p.production_status in ('active', 'discontinued') and p.availability_status in ('available', 'out_of_stock')
    and exists (select 1 from public.product_variants v where v.product_id = p.id and v.archived_at is null
                and v.publication_status = 'published' and v.variant_kind = 'decant')
    and (select count(*) from public.product_categories pc join public.categories c on c.id = pc.category_id
         where pc.product_id = p.id and c.kind = 'commercial_type' and c.publication_status = 'published'
           and c.archived_at is null) = 1
), published as (
  update public.products p set publication_status = 'published' from ready r where p.id = r.id returning p.id
)
select r.id, r.business_unit_id, r.slug from ready r join published using (id);

insert into public.audit_log (business_unit_id, actor_user_id, action, entity_type, entity_id, before, after, request_id)
select business_unit_id, null, 'publish', 'product', id, jsonb_build_object('publication_status', 'draft'),
  jsonb_build_object('publication_status', 'published', 'decision', 'owner_delegated_launch',
    'note', 'Publicado sin depender de una foto opcional: la tienda muestra "Foto próximamente" hasta que se suba la foto real (Admin → Productos → Fotos).'),
  'owner_launch_merchandising_2026-10-01'
from olm_products;

-- 3. report
select 'variants_promoted' as item, count(*)::text as value from olm_promoted
union all select 'products_published: ' || slug, 'ok' from olm_products
union all select 'bottle_variants_still_draft: ' || p.slug || ' ' || v.size_ml::text, v.price_verification_status
  from public.product_variants v join public.products p on p.id = v.product_id
  join public.business_units b on b.id = p.business_unit_id and b.code = 'parfums'
  where v.variant_kind = 'bottle' and v.publication_status = 'draft' and v.archived_at is null
order by 1;

commit;
