"use server";
import { revalidatePath } from "next/cache";
import { requireUnitAdmin } from "@/lib/auth/admin-session";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { AdminImportCatalogRepository } from "@/domains/admin-import/catalog-repository";
import { validateImportProductInput,validatePresentationInput } from "@/domains/admin-import/catalog-schema";

export type ImportCatalogActionState={ok:true;updatedAt:string}|{ok:false;message:string;errors?:Record<string,string>};
const uuid=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
async function repo(){const auth=await requireUnitAdmin("import");if(!auth.ok)return null;const client=await createSupabaseServerClient();return client?new AdminImportCatalogRepository(client,auth.membership.businessUnitId):null;}
function message(error:{type:string}){return error.type==="conflict"?"El registro cambió en otra sesión. Recarga antes de continuar.":error.type==="forbidden"?"No tienes permiso de administrador para Cruzial Import.":error.type==="not_found"?"El registro no existe o no pertenece a Cruzial Import.":"No se pudo guardar. Revisa los datos e intenta de nuevo.";}
export async function updateImportProductAction(id:string,expected:string,raw:Record<string,unknown>):Promise<ImportCatalogActionState>{if(!uuid(id)||!Date.parse(expected))return{ok:false,message:"Versión inválida. Recarga la página."};const valid=validateImportProductInput(raw);if(!valid.ok)return{ok:false,message:"Revisa los campos.",errors:valid.errors};const r=await repo();if(!r)return{ok:false,message:"No tienes permiso de administrador para Cruzial Import."};const result=await r.updateProduct(id,expected,valid.value);if(!result.ok)return{ok:false,message:message(result.error)};revalidatePath(`/admin/import/productos/${id}`);revalidatePath("/admin/import/productos");revalidatePath("/admin/import");return{ok:true,updatedAt:result.data.updated_at};}
export async function lifecycleImportProductAction(id:string,expected:string,restore:boolean):Promise<ImportCatalogActionState>{if(!uuid(id)||!Date.parse(expected))return{ok:false,message:"Versión inválida. Recarga la página."};const r=await repo();if(!r)return{ok:false,message:"No autorizado."};const result=await r.archiveProduct(id,expected,restore);if(!result.ok)return{ok:false,message:message(result.error)};revalidatePath(`/admin/import/productos/${id}`);revalidatePath("/admin/import/productos");return{ok:true,updatedAt:result.data.updated_at};}
export async function createImportPresentationAction(productId:string,raw:Record<string,unknown>):Promise<ImportCatalogActionState>{if(!uuid(productId))return{ok:false,message:"Producto inválido."};const valid=validatePresentationInput(raw,false);if(!valid.ok)return{ok:false,message:"Revisa los campos.",errors:valid.errors};const r=await repo();if(!r)return{ok:false,message:"No autorizado."};const result=await r.createPresentation(productId,valid.value);if(!result.ok)return{ok:false,message:message(result.error)};revalidatePath(`/admin/import/productos/${productId}`);revalidatePath("/admin/import");return{ok:true,updatedAt:result.data.updated_at};}
export async function updateImportPresentationAction(productId:string,id:string,expected:string,raw:Record<string,unknown>):Promise<ImportCatalogActionState>{if(!uuid(productId)||!uuid(id)||!Date.parse(expected))return{ok:false,message:"Versión inválida."};const valid=validatePresentationInput(raw,true);if(!valid.ok)return{ok:false,message:"Revisa los campos.",errors:valid.errors};const r=await repo();if(!r)return{ok:false,message:"No autorizado."};const result=await r.updatePresentation(id,expected,valid.value);if(!result.ok)return{ok:false,message:message(result.error)};revalidatePath(`/admin/import/productos/${productId}`);return{ok:true,updatedAt:result.data.updated_at};}
export async function lifecycleImportPresentationAction(productId:string,id:string,expected:string,restore:boolean):Promise<ImportCatalogActionState>{if(!uuid(productId)||!uuid(id)||!Date.parse(expected))return{ok:false,message:"Versión inválida."};const r=await repo();if(!r)return{ok:false,message:"No autorizado."};const result=await r.archivePresentation(id,expected,restore);if(!result.ok)return{ok:false,message:message(result.error)};revalidatePath(`/admin/import/productos/${productId}`);revalidatePath("/admin/import");return{ok:true,updatedAt:result.data.updated_at};}
