"use client";
import {useState,useTransition} from "react";
import Link from "next/link";
import type {Route} from "next";
import {useRouter} from "next/navigation";
import {AVAILABILITY_LABELS,type CampaignProductAvailability} from "@/domains/admin-import/campaign-products-schema";
import type {ImportProductDetail} from "@/domains/admin-import/catalog-repository";
import {PRESENTATION_CLASS_LABELS,PRESENTATION_STATUS_LABELS,PRODUCT_STATUS_LABELS} from "@/domains/admin-import/catalog-schema";
import {createImportPresentationAction,lifecycleImportPresentationAction,lifecycleImportProductAction,updateImportPresentationAction,updateImportProductAction} from "./actions";
import {PresentationOfferForm} from "./presentation-offer-form";
import styles from "./page.module.css";

export function ImportProductEditor({detail,readOnly}:{detail:ImportProductDetail;readOnly:boolean}){
 const router=useRouter();
 const [productVersion,setProductVersion]=useState(detail.product.updated_at); const [pending,start]=useTransition(); const [message,setMessage]=useState("");
 const submitProduct=(form:FormData)=>start(async()=>{setMessage("");const r=await updateImportProductAction(detail.product.id,productVersion,Object.fromEntries(form));setMessage(r.ok?"Producto guardado.":r.message+(r.errors?" "+Object.values(r.errors).join(" "):""));if(r.ok){setProductVersion(r.updatedAt);router.refresh();}});
 const lifecycle=()=>start(async()=>{const r=await lifecycleImportProductAction(detail.product.id,productVersion,!!detail.product.archived_at);setMessage(r.ok?"Estado actualizado.":r.message+(r.errors?" "+Object.values(r.errors).join(" "):""));if(r.ok){setProductVersion(r.updatedAt);router.refresh();}});
 return <>
  <section className={styles.panel}><h2>Datos del producto</h2><form onSubmit={e=>{e.preventDefault();submitProduct(new FormData(e.currentTarget));}} className={styles.form}>
   <label>Nombre<input name="name" defaultValue={detail.product.name} disabled={readOnly||!!detail.product.archived_at} required maxLength={180}/></label>
   <label>Marca<input name="brand" defaultValue={detail.product.brand??""} disabled={readOnly||!!detail.product.archived_at} maxLength={120}/></label>
   <label>Categoría Import<select name="categoryId" defaultValue={detail.category?.id??""} disabled={readOnly||!!detail.product.archived_at}><option value="">Sin categoría confirmada</option>{detail.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
   <label>Publicación<select name="publicationStatus" defaultValue={detail.product.publication_status} disabled={readOnly||!!detail.product.archived_at}>{(["draft","published","hidden"] as const).map(s=><option key={s} value={s}>{PRODUCT_STATUS_LABELS[s]}</option>)}</select></label>
   {!readOnly&&!detail.product.archived_at?<button disabled={pending}> {pending?"Guardando…":"Guardar producto"}</button>:null}
  </form>{!readOnly?<button className={styles.danger} disabled={pending} onClick={lifecycle}>{detail.product.archived_at?"Restaurar como borrador":"Archivar producto"}</button>:null}{message?<p role="status" className={styles.feedback}>{message}</p>:null}</section>
  <section className={styles.panel}><h2>Presentaciones ({detail.presentations.length})</h2><p className={styles.help}>Precio, moneda y disponibilidad se administran en el consolidado; nunca forman parte de la presentación.</p>
   <div className={styles.presentationList}>{detail.presentations.map(p=><PresentationCard key={p.id} productId={detail.product.id} presentation={p} campaignId={detail.activeCampaignId} campaignNumber={detail.activeCampaignNumber} campaignVersion={detail.activeCampaignUpdatedAt} readOnly={readOnly||!!detail.product.archived_at}/>)}</div>
   {!readOnly&&!detail.product.archived_at?<CreatePresentation productId={detail.product.id}/>:null}
  </section>
 </>;
}
function PresentationCard({productId,presentation:p,campaignId,campaignNumber,campaignVersion,readOnly}:{productId:string;presentation:ImportProductDetail["presentations"][number];campaignId:string|null;campaignNumber:number|null;campaignVersion:string|null;readOnly:boolean}){const router=useRouter();const [version,setVersion]=useState(p.updated_at);const [pending,start]=useTransition();const [message,setMessage]=useState("");const submit=(f:FormData)=>start(async()=>{const r=await updateImportPresentationAction(productId,p.id,version,Object.fromEntries(f));setMessage(r.ok?"Presentación guardada.":r.message+(r.errors?" "+Object.values(r.errors).join(" "):""));if(r.ok){setVersion(r.updatedAt);router.refresh();}});const lifecycle=()=>start(async()=>{const r=await lifecycleImportPresentationAction(productId,p.id,version,!!p.archived_at);setMessage(r.ok?"Estado actualizado.":r.message+(r.errors?" "+Object.values(r.errors).join(" "):""));if(r.ok){setVersion(r.updatedAt);router.refresh();}});return <article className={styles.presentation}><form onSubmit={e=>{e.preventDefault();submit(new FormData(e.currentTarget));}} className={styles.form}>
 <label>Etiqueta<input name="label" defaultValue={p.label} disabled={readOnly||!!p.archived_at}/></label><label>Clase<select name="presentationClass" defaultValue={p.presentation_class} disabled={readOnly||!!p.archived_at}>{Object.entries(PRESENTATION_CLASS_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Capacidad ml<input name="capacityMl" inputMode="decimal" defaultValue={p.capacity_ml??""} disabled={readOnly||!!p.archived_at}/></label><label>Publicación<select name="publicationStatus" defaultValue={p.publication_status} disabled={readOnly||!!p.archived_at}><option value="draft">{PRESENTATION_STATUS_LABELS.draft}</option><option value="published">{PRESENTATION_STATUS_LABELS.published}</option></select></label>
 {!readOnly&&!p.archived_at?<button disabled={pending}>{pending?"Guardando…":"Guardar"}</button>:null}</form><div className={styles.offer}>{p.offer?`Consolidado #${campaignNumber}: ${p.offer.currency} ${p.offer.price_amount} · ${AVAILABILITY_LABELS[p.offer.availability_status as CampaignProductAvailability]??"Por confirmar"}`:campaignNumber!==null?`Sin oferta en el consolidado #${campaignNumber}`:"Selecciona un consolidado para gestionar ofertas"}{campaignId?<p><Link href={`/admin/import/consolidados/${campaignId}` as Route}>Gestionar ofertas, precios y disponibilidad de este consolidado</Link></p>:null}</div>{p.offer&&campaignId&&campaignVersion&&!readOnly&&!p.archived_at?<PresentationOfferForm key={campaignVersion} campaignId={campaignId} version={campaignVersion} productId={productId} presentationId={p.id} price={String(p.offer.price_amount)} currency={p.offer.currency} availability={p.offer.availability_status}/>:null}{!readOnly?<button className={styles.danger} disabled={pending} onClick={lifecycle}>{p.archived_at?"Restaurar como borrador":"Archivar presentación"}</button>:null}{message?<p role="status" className={styles.feedback}>{message}</p>:null}</article>}
function CreatePresentation({productId}:{productId:string}){const router=useRouter();const[pending,start]=useTransition();const[message,setMessage]=useState("");return <form className={`${styles.form} ${styles.create}`} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);start(async()=>{const r=await createImportPresentationAction(productId,Object.fromEntries(f));setMessage(r.ok?"Presentación creada en borrador.":r.message+(r.errors?" "+Object.values(r.errors).join(" "):""));if(r.ok)router.refresh();});}}><h3>Nueva presentación</h3><label>Etiqueta<input name="label" required/></label><label>Clase<select name="presentationClass" defaultValue="single_fixed">{Object.entries(PRESENTATION_CLASS_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Capacidad ml (opcional)<input name="capacityMl" inputMode="decimal"/></label><button disabled={pending}>{pending?"Creando…":"Crear en borrador"}</button>{message?<p role="status" className={styles.feedback}>{message}</p>:null}</form>}
