import type {Metadata,Route} from "next";import Link from "next/link";import {redirect} from "next/navigation";
import {getAdminSession} from "@/lib/auth/admin-session";import {createSupabaseServerClient} from "@/lib/supabase/server";import {AdminImportCatalogRepository} from "@/domains/admin-import/catalog-repository";import {classifyProductReadiness,parseImportCatalogFilters,PRODUCT_STATUS_LABELS,type ImportProductStatus} from "@/domains/admin-import/catalog-schema";import {campaignStatusLabel} from "@/domains/admin-import/campaign-schema";import styles from "./page.module.css";
export const dynamic="force-dynamic";export const metadata:Metadata={title:"Productos Import"};
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const session=await getAdminSession();if(session.status==="signed_out")redirect("/admin/login");if(session.status!=="ok")redirect("/admin");const member=session.session.memberships.find(m=>m.businessUnitCode==="import");if(!member)redirect("/admin");const client=await createSupabaseServerClient();if(!client)redirect("/admin");const raw=await searchParams;const filters=parseImportCatalogFilters(raw);const repo=new AdminImportCatalogRepository(client,member.businessUnitId);
// Which consolidado (campaign) is being evaluated must be explicit — never
// an implicit "current campaign" guess. ?campaign=<uuid> preserves the
// operator's choice across filters, pagination, and product-detail links.
const campaignsResult=await client.from("campaigns").select("id,number,name,status,archived_at").eq("business_unit_id",member.businessUnitId).is("archived_at",null).order("number",{ascending:false});
const campaigns=campaignsResult.data??[];
const requestedCampaignId=typeof raw.campaign==="string"?raw.campaign:"";
const selectedCampaign=campaigns.find(c=>c.id===requestedCampaignId)??campaigns[0]??null;
const [result,categories,qa]=await Promise.all([selectedCampaign?repo.list(filters,selectedCampaign.id):Promise.resolve({ok:true as const,data:{items:[],total:0}}),client.from("categories").select("name,slug").eq("business_unit_id",member.businessUnitId).eq("kind","import_category").is("archived_at",null).order("name"),repo.qa()]);
if(!result.ok)return <main className={styles.page}><p className={styles.error}>No se pudo cargar el catálogo Import.</p></main>;
const totalPages=Math.max(1,Math.ceil(result.data.total/filters.pageSize));
const campaignQuery=selectedCampaign?`&campaign=${selectedCampaign.id}`:"";
const href=(page:number)=>{const p=new URLSearchParams();for(const[k,v]of Object.entries(raw))if(typeof v==="string")p.set(k,v);if(selectedCampaign)p.set("campaign",selectedCampaign.id);p.set("page",String(page));return`?${p}` as Route};
const productHref=(id:string)=>`/admin/import/productos/${id}${campaignQuery?`?${campaignQuery.slice(1)}`:""}` as Route;
return <div className={styles.page}><header className={styles.header}><div><Link className={styles.back} href="/admin/import">← Cruzial Import</Link><h1>Productos</h1><p>{result.data.total} resultados · páginas acotadas de {filters.pageSize}</p></div></header><main>
<section className={styles.panel} aria-label="Consolidado evaluado">
  {campaigns.length>0?<form method="get" className={styles.filters}>
    {Object.entries(raw).filter(([k,v])=>k!=="campaign"&&k!=="page"&&typeof v==="string").map(([k,v])=><input key={k} type="hidden" name={k} value={v as string}/>)}
    <label><span className={styles.help}>Consolidado evaluado</span><select name="campaign" defaultValue={selectedCampaign?.id}>
      {campaigns.map(c=><option key={c.id} value={c.id}>#{c.number} — {c.name} ({campaignStatusLabel(c.status)})</option>)}
    </select></label>
    <button>Ver este consolidado</button>
  </form>:<p className={styles.help}>No hay consolidados activos (no archivados) para Cruzial Import. Crea uno desde <Link href="/admin/import/consolidados">Consolidados</Link>.</p>}
</section>
<form className={styles.filters}>
  {selectedCampaign?<input type="hidden" name="campaign" value={selectedCampaign.id}/>:null}
  <label><span className={styles.help}>Buscar</span><input name="q" defaultValue={filters.query} placeholder="Nombre, marca o identidad canónica"/></label><label><span className={styles.help}>Publicación</span><select name="status" defaultValue={filters.publicationStatus??""}><option value="">Todos</option>{Object.entries(PRODUCT_STATUS_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><span className={styles.help}>Categoría</span><select name="category" defaultValue={filters.categorySlug??""}><option value="">Todas</option>{(categories.data??[]).map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select></label><label><span className={styles.help}>Media</span><select name="media" defaultValue={filters.mediaState??""}><option value="">Todas</option><option value="with_primary">Con imagen principal</option><option value="without_primary">Sin imagen principal</option><option value="without_media">Sin imagen</option></select></label><label><span className={styles.help}>Presentación</span><select name="presentation" defaultValue={filters.presentationState??""}><option value="">Todas</option><option value="with_active">Con activa</option><option value="without_active">Sin activa</option><option value="without_published">Sin publicada</option></select></label><label><span className={styles.help}>Oferta en consolidado evaluado</span><select name="offer" defaultValue={filters.offerState??""}><option value="">Todas</option><option value="with_offer">Con oferta</option><option value="without_offer">Sin oferta</option></select></label><label><span className={styles.help}>Archivo</span><select name="archived" defaultValue={filters.archived}><option value="active">Activos</option><option value="archived">Archivados</option><option value="all">Todos</option></select></label><button>Aplicar</button></form>
{qa.ok?<section className={styles.qaGrid} aria-label="Estado del catálogo"><div className={styles.qaCard}><strong>{qa.data.products}</strong><span>productos activos</span></div><div className={styles.qaCard}><strong>{qa.data.presentations}</strong><span>presentaciones activas</span></div><div className={styles.qaCard}><strong>{qa.data.campaign_offers}</strong><span>{qa.data.campaign_number!==null?`ofertas en #${qa.data.campaign_number} (consolidado más reciente)`:"ofertas (sin consolidado activo)"}</span></div><div className={styles.qaCard}><strong>{qa.data.structures_without_offer}</strong><span>estructuras sin oferta</span></div><div className={`${styles.qaCard} ${Number(qa.data.products_without_primary_media)>0?styles.warning:""}`}><strong>{qa.data.products_without_primary_media}</strong><span>sin imagen principal</span></div><div className={`${styles.qaCard} ${Number(qa.data.products_without_media)>0?styles.warning:""}`}><strong>{qa.data.products_without_media}</strong><span>sin media</span></div></section>:null}
{result.data.items.length===0?<p className={styles.empty}>{selectedCampaign?"No hay productos que coincidan con estos filtros.":"Selecciona un consolidado para ver productos y ofertas."}</p>:<ul className={styles.list}>{result.data.items.map(item=>{const ready=classifyProductReadiness({productStatus:item.publication_status as ImportProductStatus,archived:!!item.archived_at,activePresentations:Number(item.active_presentations),publishedPresentations:Number(item.published_presentations),offerCount:Number(item.campaign_offer_count),unconfirmedOfferCount:Number(item.unconfirmed_offer_count),campaignStatus:selectedCampaign?.status??null});const mediaBadge=item.has_active_primary?"Con principal":item.active_media_count>0?"Sin principal":"Sin media";const mediaClass=item.has_active_primary?"":item.active_media_count>0?styles.warning:"";return <li className={styles.row} key={item.id}><Link href={productHref(item.id)}><div><strong>{item.name}</strong><div className={styles.meta}><span>{item.brand??"Sin marca"}</span><span>{item.category_name??"Sin categoría"}</span><span>{item.active_presentations} presentaciones</span></div></div><div className={styles.badges}><span className={styles.badge}>{PRODUCT_STATUS_LABELS[item.publication_status as keyof typeof PRODUCT_STATUS_LABELS]??item.publication_status}</span><span className={`${styles.badge} ${mediaClass}`}>{mediaBadge}</span><span className={`${styles.badge} ${ready.blockers.length?styles.warning:styles.good}`}>{ready.blockers[0]??"Listo estructuralmente"}</span></div></Link></li>})}</ul>}
{totalPages>1?<nav className={styles.pagination} aria-label="Paginación">{filters.page>1?<Link href={href(filters.page-1)} scroll={false}>← Anterior</Link>:<span>← Anterior</span>}<span>Página {filters.page} de {totalPages}</span>{filters.page<totalPages?<Link href={href(filters.page+1)} scroll={false}>Siguiente →</Link>:<span>Siguiente →</span>}</nav>:null}</main></div>}
